customers-service:
  - 'apps/customers-service/**'
  - 'packages/shared/**'
  - 'packages/database/**'
  - 'packages/config/**'
  - 'docker/Dockerfile.service'
  - 'pnpm-lock.yaml'
  - 'package.json'
  - 'pnpm-workspace.yaml'
  - 'turbo.json'

inventory-service:
  - 'apps/inventory-service/**'
  - 'packages/shared/**'
  - 'packages/database/**'
  - 'packages/events/**'
  - 'packages/config/**'
  - 'docker/Dockerfile.service'
  - 'pnpm-lock.yaml'
  - 'package.json'
  - 'pnpm-workspace.yaml'
  - 'turbo.json'

orders-service:
  - 'apps/orders-service/**'
  - 'packages/shared/**'
  - 'packages/database/**'
  - 'packages/events/**'
  - 'packages/config/**'
  - 'docker/Dockerfile.service'
  - 'pnpm-lock.yaml'
  - 'package.json'
  - 'pnpm-workspace.yaml'
  - 'turbo.json'

catalog-service:
  - 'apps/catalog-service/**'
  - 'packages/shared/**'
  - 'packages/config/**'
  - 'docker/Dockerfile.service'
  - 'pnpm-lock.yaml'
  - 'package.json'
  - 'pnpm-workspace.yaml'
  - 'turbo.json'

seed-runner:
  - 'packages/seed/**'
  - 'packages/database/**'
  - 'packages/shared/**'
  - 'packages/config/**'
  - 'data/demo/**'
  - 'docker/Dockerfile.seed'
  - 'pnpm-lock.yaml'
  - 'package.json'
  - 'pnpm-workspace.yaml'

seed-data:
  - 'packages/database/prisma/migrations/**'
  - 'packages/database/prisma/seed.ts'
  - 'packages/database/prisma/schema.prisma'
  - 'packages/seed/**'
  - 'data/demo/**'

terraform:
  - 'iac/**'

workflows:
  - '.github/workflows/**'
