# Identificador del proyecto (debe coincidir con el Project key)
sonar.projectKey=distrinorte
sonar.projectName=DistriNorte
sonar.projectVersion=1.0
# Dónde está el código fuente (relativo a este archivo)
sonar.sources=iac
# Codificación de los archivos
sonar.sourceEncoding=UTF-8
# URL del servidor SonarQube
sonar.host.url=http://localhost:9000