# syntax=docker/dockerfile:1

FROM node:24-alpine AS base
RUN apk add --no-cache libc6-compat
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@9.15.4 --activate
WORKDIR /app

FROM base AS pruner
ARG SERVICE
RUN pnpm add -g turbo@2.9.18
COPY . .
RUN turbo prune @distrinorte/${SERVICE} --docker

FROM base AS deps
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile

FROM deps AS builder
ARG SERVICE
COPY --from=pruner /app/out/full/ .
RUN pnpm --filter @distrinorte/database db:generate
RUN pnpm turbo run build --filter=@distrinorte/${SERVICE}

FROM base AS runner
ARG SERVICE
ENV NODE_ENV=production
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nestjs --ingroup nodejs

COPY --from=builder --chown=nestjs:nodejs /app/ .

USER nestjs
WORKDIR /app/apps/${SERVICE}

EXPOSE 3000
CMD ["node", "dist/main.js"]
